name: Deploy
description: Deploys new Lambda function code
inputs:
  aws-access-key-id:
    description: AWS access key
    required: true
  aws-secret-access-key:
    description: AWS secret key
    required: true
  dry-run:
    description: >-
      If truthy, the deploy will be a dry run, or will not be attempted at all
      if `aws-access-key-id` is blank (instead of erroring)
    required: false
    default: ""
  environment:
    description: Name of the environment to deploy to (dev/prod)
    required: true
runs:
  using: composite
  steps:
    - uses: ./.github/actions/deps

    - run: ./build.sh src/packager.ts
      shell: bash
    - run: ./build.sh src/processor.ts
      shell: bash

    - run: >-
        aws lambda update-function-code
        --function-name ocs-saver-${{ inputs.environment }}-packager
        --zip-file fileb://dist/packager.zip
        ${{ inputs.dry-run && '--dry-run' || '' }}
      shell: bash
      if: ${{ !inputs.dry-run || inputs.aws-access-key-id }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1

    - run: >-
        aws lambda update-function-code
        --function-name ocs-saver-${{ inputs.environment }}-firehose-processor
        --zip-file fileb://dist/processor.zip
        ${{ inputs.dry-run && '--dry-run' || '' }}
      shell: bash
      if: ${{ !inputs.dry-run || inputs.aws-access-key-id }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1
