name: Deploy
description: Deploys new Lambda function code

permissions:
  id-token: write

inputs:
  dry-run:
    description: >-
      If truthy, the deploy will be a dry run, or will not be attempted at all
      if `role-to-assume` is blank (instead of erroring)
    required: false
    default: ""
  environment:
    description: Name of the environment to deploy to (dev/prod)
    required: true
runs:
  using: composite
  steps:

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.role-to-assume }}
        aws-region: 'us-east-1'

    - uses: ./.github/actions/deps

    - run: ./build.sh src/packager.ts
      shell: bash
    - run: ./build.sh src/processor.ts
      shell: bash

    - run: >-
        aws lambda update-function-code
        --function-name ocs-saver-${{ inputs.environment }}-packager
        --zip-file fileb://dist/packager.zip
        ${{ inputs.dry-run && '--dry-run' || '' }}
      shell: bash
      if: ${{ !inputs.dry-run }}

    - run: >-
        aws lambda update-function-code
        --function-name ocs-saver-${{ inputs.environment }}-firehose-processor
        --zip-file fileb://dist/processor.zip
        ${{ inputs.dry-run && '--dry-run' || '' }}
      shell: bash
      if: ${{ !inputs.dry-run }}
