name: Deploy
description: Deploys new Lambda function code
inputs:
  aws-access-key-id:
    description: AWS access key
    required: true
  aws-secret-access-key:
    description: AWS secret key
    required: true
  environment:
    description: Name of the environment to deploy to (dev/prod)
    required: true
  options:
    description: Extra options to be passed to the `aws` commands
    required: false
    default: ""
runs:
  using: composite
  steps:
    - uses: ./.github/actions/deps

    - run: ./build.sh src/packager.ts
      shell: bash
    - run: ./build.sh src/processor.ts
      shell: bash

    - run: >-
        aws lambda update-function-code
        --function-name ocs-saver-${{ inputs.environment }}-packager
        --zip-file fileb://dist/packager.zip
        ${{ inputs.options }}
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1

    - run: >-
        aws lambda update-function-code
        --function-name ocs-saver-${{ inputs.environment }}-firehose-processor
        --zip-file fileb://dist/processor.zip
        ${{ inputs.options }}
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1
