name: Set up tools
description: Loads asdf tools for a CI job, installing them if not cached
runs:
  using: composite
  steps:
    - uses: actions/cache@v2
      id: asdf-cache
      with:
        path: ~/.asdf
        key: ${{ env.CACHE_UUID }}-asdf-${{ hashFiles('.tool-versions') }}

    - uses: asdf-vm/actions/install@v1
      if: "!steps.asdf-cache.outputs.cache-hit"

    - uses: mbta/actions/reshim-asdf@v1
