name: Deploy to Dev

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: >-
      ${{
        github.event_name == 'workflow_dispatch' ||
        github.event.workflow_run.conclusion == 'success'
      }}
    environment: dev
    concurrency: deploy-dev

    steps:
      - uses: actions/checkout@v2
      - run: echo "Not implemented"
