name: Deploy to Prod

on:
  workflow_dispatch:

env:
  CACHE_UUID: ${{ secrets.CACHE_UUID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: prod
    concurrency: deploy-prod

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          environment: prod
