name: Deploy to Dev

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

env:
  CACHE_UUID: ${{ secrets.CACHE_UUID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: >-
      ${{
        github.event_name == 'workflow_dispatch' ||
        github.event.workflow_run.conclusion == 'success'
      }}
    environment: dev
    concurrency: deploy-dev

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          aws-role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          environment: dev
