name: Deploy to Prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: prod
    concurrency: deploy-prod

    steps:
      - uses: actions/checkout@v2
      - run: echo "Not implemented"
